import { defineConfig, Plugin } from 'vite';
import path from 'path';
import fs from 'node:fs';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';

// ─────────────────────────────────────────────────────────────────────────────
// figmaAssetPlugin
//
// Resolves Figma Make's virtual "figma:asset/HASH.ext" imports to the actual
// image files stored under src/imports/**. This makes `figma:asset` imports
// work in a standard Vite build without any manual path changes.
//
// Usage in components (generated by Figma Make):
//   import mascot from "figma:asset/9ae95f1586357c068ebf21aa31af5d656f0795b3.png";
// ─────────────────────────────────────────────────────────────────────────────
function figmaAssetPlugin(): Plugin {
  const importsDir = path.resolve(__dirname, 'src/imports');

  function findFileRecursive(dir: string, filename: string): string | null {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return null;
    }
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        const found = findFileRecursive(fullPath, filename);
        if (found) return found;
      } else if (entry.name === filename) {
        return fullPath;
      }
    }
    return null;
  }

  return {
    name: 'figma-asset',
    enforce: 'pre',
    resolveId(id) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.slice('figma:asset/'.length);
        return findFileRecursive(importsDir, filename) ?? null;
      }
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), figmaAssetPlugin()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  // Supported raw-import asset types
  assetsInclude: ['**/*.svg', '**/*.csv'],
});
